server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/authdb

  jwt:
    secret: "your-very-secure-secret-key-which-is-long"
    expiration: 900000 # 15 minutes

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

mongock:
  migration-scan-package:
    - com.platform.auth.migration
  enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  ratelimiter:
    instances:
      registerLimiter:
        limit-for-period: 3
        limit-refresh-period: 1m
        timeout-duration: 0
      loginLimiter:
        limit-for-period: 5
        limit-refresh-period: 1m
        timeout-duration: 0
      refreshLimiter:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 0
  retry:
    instances:
      notificationProducerRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.lang.RuntimeException
