server:
  port: 8085

spring:
  application:
    name: NOTIFICATION-SERVICE
  
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: "notificationRequestedEvent:com.platform.common.event.NotificationRequestedEvent"
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  ratelimiter:
    instances:
      emailNotificationLimiter:
        limit-for-period: 20
        limit-refresh-period: 1m
        timeout-duration: 0
      smsNotificationLimiter:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 0
      whatsAppMessageNotificationLimiter:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 0
  circuitbreaker:
    instances:
      emailNotificationCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
      smsNotificationCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
      whatsAppMessageNotificationCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      emailNotificationRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.lang.RuntimeException
      smsNotificationRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.lang.RuntimeException
      whatsAppMessageNotificationRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.lang.RuntimeException

twilio:
  phone: whatsapp:+14155238886