server:
  port: 8080

spring:
  application:
    name: catalogue-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/cataloguedb

  jackson:
    serialization:
      write-dates-as-timestamps: false

# Mongock Configuration
mongock:
  migration-scan-package:
    - com.platform.catalogue.migration

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO