server:
  port: 8080

spring:
  application:
    name: ticket-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/ticketdb

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

  jackson:
    serialization:
      write-dates-as-timestamps: false

# Mongock
mongock:
  migration-scan-package:
    - com.platform.ticket.migration

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

# Custom Topics
kafka:
  topics:
    notification: notification.requested

logging:
  level:
    root: INFO